# Generated by Django 5.2.17 on 2026-09-09 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0002_document_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matter',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='multi_assigned_matters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='multi_assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
